name: nginx-ingress-pull
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        required: true
        default: 4.8.0
permissions: {}

env:
  GH_TOKEN: ${{ github.token }}
jobs:
  ingress-nginx-pull:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download Chart
        run: |
          set -euxo pipefail
          curl -fLO "https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-${{ inputs.chartVersion}}/ingress-nginx-${{ inputs.chartVersion}}.tgz"
          tar zxvf ingress-nginx-${{inputs.chartVersion}}.tgz --directory /tmp
          rm -fv ingress-nginx-${{inputs.chartVersion}}.tgz
          mkdir -p ingress-nginx/v${{inputs.chartVersion}}
          cp -pr /tmp/ingress-nginx/* ingress-nginx/v${{inputs.chartVersion}}
          ls -l ingress-nginx/v${{inputs.chartVersion}}
      - name: Push to Github Repo
        run: |
          set -euxo pipefail
          git config user.name github-actions
          git config user.email githubactions@github.com
          git checkout -b helm-ingress-nginx-v${{inputs.chartVersion}}
          git add ingress-nginx/v${{inputs.chartVersion}}
          git commit -m "added chart for ingress nginx v${{inputs.chartVersion}}"
          git push origin helm-ingress-nginx-v${{inputs.chartVersion}}
      - name: Sleep for Five
        run: sleep 5
      - name: Create PR
        run: |
          set -euxo pipefail
          gh pr create \
          --base main \
          --head helm-ingress-nginx-v${{inputs.chartVersion}} \
          --label nginx-helm-pull \
          --title 'Helm Chart for ingress-nginx v${{inputs.chartVersion}}' \
          --body 'Created by ${{ github.workflow }} workflow' \